# main.py (Backend - Streamlit and Gemini API)
import streamlit as st
import google.generativeai as genai
from google.genai import types
import tempfile
import os
from PyPDF2 import PdfReader

# Configure Gemini API
GOOGLE_API_KEY = st.secrets["GOOGLE_API_KEY"]
genai.configure(api_key=GOOGLE_API_KEY)
model = genai.GenerativeModel('gemini-2.0-flash')



def extract_text_from_pdf(pdf_file):
    """Extracts text from a PDF file."""
    try:
        pdf_reader = PdfReader(pdf_file)
        text = ""
        for page_num in range(len(pdf_reader.pages)):
            page = pdf_reader.pages[page_num]
            text += page.extract_text()
        return text
    except Exception as e:
        return f"Error extracting text: {e}"

def generate_implementing_law(bit_text):
    """Generates a draft project of law to implement the BIT."""
    try:
        prompt = f"""
        Based on the following Bilateral Investment Treaty (BIT) document, draft a detailed project of law that would implement the treaty into national legislation. The project of law should cover all key aspects of the BIT, including definitions, scope of application, investor protections (such as fair and equitable treatment, national treatment, most-favored-nation treatment, expropriation, compensation), dispute settlement mechanisms, and any other relevant provisions.

        The project of law should be structured with clear articles and sections, using legal terminology appropriate for national legislation. Aim for the most comprehensive and detailed implementation possible, ensuring clarity and enforceability of the BIT's provisions within the national legal framework.

        BIT Document:
        {bit_text}

        Project of Law:
        """
        response = model.generate_content(prompt,
                                         generation_config=genai.types.GenerationConfig(
                                             max_output_tokens=2048,  # Increase for potentially longer output
                                             temperature=0.4,       # Adjust for creativity vs. accuracy
                                         ))
        return response.text
    except Exception as e:
        return f"Error generating the project of law: {e}"

def main():
    st.title("BIT Implementation Law Generator")
    st.subheader("Generate a draft project of law to implement a Bilateral Investment Treaty (BIT).")

    uploaded_file = st.file_uploader("Upload a BIT document (PDF)", type=["pdf"], key="law_file")

    if uploaded_file is not None:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as temp_file:
            temp_file.write(uploaded_file.getvalue())
            temp_file_path = temp_file.name
            bit_text = extract_text_from_pdf(temp_file_path)
            os.unlink(temp_file_path)

            if "Error" in bit_text:
                st.error(f"Error processing the document: {bit_text}")
                return

            if st.button("Generate Implementing Law"):
                with st.spinner("Generating the project of law..."):
                    implementing_law_draft = generate_implementing_law(bit_text)
                    st.subheader("Draft Project of Law:")
                    st.code(implementing_law_draft, language="python")  # Display as code for better formatting
                    st.info("This is a draft generated by AI and should be reviewed and adapted by legal professionals.")

    else:
        st.info("Please upload a BIT document to generate the implementing law.")

if __name__ == "__main__":
    main()